syntax = "proto3";
import "google/protobuf/timestamp.proto";
option csharp_namespace = "GrpcCon";

package customer.v1;

service Customer {
  rpc Create (CreateCustomerRequest) returns (CreateCustomerReply);
   rpc GetCustomer (CreateCustomerRequest) returns (stream CreateCustomerReply);
}

message CreateCustomerRequest {
  string name = 1;
  optional int32 age = 2;
  Gender gender = 3;
}

message CreateCustomerReply {
  string message = 1;
  google.protobuf.Timestamp created_at = 2;
}

enum Gender{
	MALE = 0;
	FEMALE =1;
}